spring:
  application:
    name: ecommerce_platform
---
spring:
  config:
    import: env.yml
---
# Server Configuration (?? ??: ?? ?? ?)
server:
  port: ${SPRING_SERVER_PORT}
---
# Spring Data Source Configuration (?????? ?? ??)
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}

  # JPA (Hibernate) Configuration
  jpa:
    hibernate:
      ddl-auto: update # ?? ???? ??? ?? ? ??? ?? ???? (?? ??? none ?? validate)
    show-sql: true # ???? SQL ??? ??? ??
    properties:
      hibernate:
        format_sql: true # SQL ??? ??? ????? ??
        dialect: org.hibernate.dialect.H2Dialect # H2 DB ?? ?? (?? ???? ????? ?? ??)

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console



